# Generated by Django 5.1.5 on 2025-02-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_alter_subject_grade_level'),
        ('teachers', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade_level', models.IntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11')])),
                ('schedule', models.CharField(choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session'), ('evening', 'Evening Session')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('max_students', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher')),
                ('subjects', models.ManyToManyField(blank=True, to='subjects.subject')),
            ],
        ),
    ]
