# Generated by Django 5.1.5 on 2025-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('subjects', '0002_alter_subject_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='subjects.subject'),
        ),
    ]
