# Generated by Django 5.1.5 on 2025-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_subjects'),
        ('students', '0002_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='students.student'),
        ),
    ]
