# Generated by Django 5.1.5 on 2025-02-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(choices=[('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade')], help_text='Select the grade level for this subject.', max_length=2),
        ),
    ]
